services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: larawell-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - larawell-network
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine
    container_name: larawell-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - larawell-network
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: larawell-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: larawell
      POSTGRES_USER: larawell
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - larawell-network

  redis:
    image: redis:alpine
    container_name: larawell-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - larawell-network

  # Sentry Services
  sentry-redis:
    image: redis:alpine
    container_name: sentry-redis
    restart: unless-stopped
    networks:
      - larawell-network

  sentry-postgres:
    image: postgres:15
    container_name: sentry-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
      - sentry-postgres:/var/lib/postgresql/data
    networks:
      - larawell-network

  sentry:
    image: sentry:latest
    container_name: sentry
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      SENTRY_SECRET_KEY: 'changeme-please-generate-a-secret-key'
      SENTRY_POSTGRES_HOST: sentry-postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: sentry-redis
    depends_on:
      - sentry-redis
      - sentry-postgres
    networks:
      - larawell-network
    volumes:
      - sentry-data:/var/lib/sentry/files

  sentry-cron:
    image: sentry:latest
    container_name: sentry-cron
    restart: unless-stopped
    command: run cron
    environment:
      SENTRY_SECRET_KEY: 'changeme-please-generate-a-secret-key'
      SENTRY_POSTGRES_HOST: sentry-postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: sentry-redis
    depends_on:
      - sentry-redis
      - sentry-postgres
    networks:
      - larawell-network
    volumes:
      - sentry-data:/var/lib/sentry/files

  sentry-worker:
    image: sentry:latest
    container_name: sentry-worker
    restart: unless-stopped
    command: run worker
    environment:
      SENTRY_SECRET_KEY: 'changeme-please-generate-a-secret-key'
      SENTRY_POSTGRES_HOST: sentry-postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: sentry-redis
    depends_on:
      - sentry-redis
      - sentry-postgres
    networks:
      - larawell-network
    volumes:
      - sentry-data:/var/lib/sentry/files

networks:
  larawell-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  sentry-postgres:
    driver: local
  sentry-data:
    driver: local
